[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_event = 'BufRead'
hook_add = '''
nmap <silent> <C-u><C-t> :<C-u>Denite -default-action=tabopen filetype<CR>
nmap <silent> <C-u><C-p> :<C-u>Denite -default-action=tabopen file_rec<CR>
nmap <silent> <C-u><C-j> :<C-u>Denite -default-action=tabopen line<CR>
nmap <silent> <C-u><C-g> :<C-u>Denite -default-action=tabopen grep<CR>
nmap <silent> <C-u><C-]> :<C-u>DeniteCursorWord -default-action=tabopen grep<CR>
nmap <silent> <C-u><C-u> :<C-u>Denite -default-action=tabopen file_mru<CR>
nmap <silent> <C-u><C-y> :<C-u>Denite -default-action=tabopen neoyank<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if   = '''has('lua')'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'sorah/unite-ghq'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-help'
on_source = 'unite.vim'

[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = 'tex'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'hallison/vim-markdown'

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'prettier/vim-prettier'

[[plugins]]
repo = 'tomlion/vim-solidity' 

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'shime/vim-livedown'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'jparise/vim-graphql'
