[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = 'tex'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'hallison/vim-markdown'

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'prettier/vim-prettier'
rev = 'release/1.x'

[[plugins]]
repo = 'tomlion/vim-solidity' 

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'shime/vim-livedown'

[[plugins]]
repo = 'jparise/vim-graphql'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'larsbs/vimterial_dark'

[[plugins]]
repo = 'udalov/kotlin-vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Quramy/tsuquyomi'

[[plugins]]
repo = "vim-airline/vim-airline"

[[plugins]]
repo = "vim-airline/vim-airline-themes"

[[plugins]]
repo = "Shougo/neosnippet.vim"
hook_add = '''
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo = "Shougo/neosnippet-snippets"

[[plugins]]
repo = "danro/rename.vim"

# git {{{

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = '''
  " use 1 to enable highlighting
  let g:gitgutter_highlight_lines = 0
'''
# }}}

[[plugins]]
repo = "rhysd/git-messenger.vim"
hook_add = '''
nnoremap <leader>gm :GitMessenger<c-r>
'''

# explorer {{{
[[plugins]]
repo = "Shougo/defx.nvim"

[[plugins]]
repo = "kristijanhusak/defx-icons"

[[plugins]]
repo = "ryanoasis/vim-devicons"
# }}}

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
nnoremap <leader>fz :Files<CR>
nnoremap <silent> <Leader>ag :Ag <C-R><C-W><CR>
'''

[[plugins]]
repo = 'lvht/mru'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'neoclide/coc.nvim'

[[plugins]]
repo = 'janko/vim-test'
add_hook = '''
nmap <silent> t<C-n> :TestNearest<CR>
nmap <silent> t<C-f> :TestFile<CR>
nmap <silent> t<C-s> :TestSuite<CR>
nmap <silent> t<C-l> :TestLast<CR>
nmap <silent> t<C-g> :TestVisit<CR>
'''
