[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = 'tex'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'hallison/vim-markdown'

[[plugins]]
repo = 'prettier/vim-prettier'
rev = 'release/1.x'
on_ft = ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html', 'svelte']

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'jparise/vim-graphql'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'larsbs/vimterial_dark'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Quramy/tsuquyomi'

[[plugins]]
repo = "vim-airline/vim-airline"

[[plugins]]
repo = "vim-airline/vim-airline-themes"

# git {{{

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = '''
  " use 1 to enable highlighting
  let g:gitgutter_highlight_lines = 0
'''

[[plugins]]
repo = "rhysd/git-messenger.vim"
hook_add = '''
nnoremap <leader>gm :GitMessenger<c-r>
'''

# }}}

# explorer {{{
[[plugins]]
repo = "Shougo/defx.nvim"

[[plugins]]
repo = "kristijanhusak/defx-icons"

[[plugins]]
repo = "ryanoasis/vim-devicons"
# }}}

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
nnoremap <leader>fz :Files<CR>
nnoremap <silent> <Leader>ag :Ag <C-R><C-W><CR>
nnoremap <leader>bb :Buffer<CR>
'''

[[plugins]]
repo = 'pbogut/fzf-mru.vim'
hook_add = '''
nnoremap <leader>mr :FZFMru<CR>
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# rev = 'release'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'cocopon/iceberg.vim'
